# Generated by Django 5.0.7 on 2024-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile/images/'),
        ),
    ]
