# Generated by Django 5.0.7 on 2024-10-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, default='https://ibb.co.com/xXrms8v', null=True),
        ),
    ]
