# Generated by Django 5.0.7 on 2024-10-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(default='https://i.ibb.co.com/YPVDWT9/empty.jpg'),
        ),
    ]
