# Generated by Django 5.0.7 on 2024-08-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_foodfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodfeedback',
            name='rating',
            field=models.IntegerField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)]),
        ),
    ]
