# Generated by Django 5.0.7 on 2024-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_fooditem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
