# Generated by Django 5.0.7 on 2024-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_foodfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodfeedback',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
