# Generated by Django 5.0.7 on 2024-08-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_foodcategory_slug_alter_fooditem_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='slug',
            new_name='restaurant_slug',
        ),
    ]
