# Generated by Django 5.0.7 on 2024-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_slug_fooditem_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images'),
        ),
    ]
