# Generated by Django 5.0.7 on 2024-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_foodfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.CharField(default='https://ibb.co.com/xXrms8v'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.CharField(default='https://ibb.co.com/xXrms8v'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.CharField(default='https://ibb.co.com/xXrms8v'),
        ),
    ]
