# Generated by Django 5.0.7 on 2024-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_foodcategory_image_alter_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.CharField(default='https://i.ibb.co.com/YPVDWT9/empty.jpg'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.CharField(default='https://i.ibb.co.com/YPVDWT9/empty.jpg'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.CharField(default='https://i.ibb.co.com/YPVDWT9/empty.jpg'),
        ),
    ]
