# Generated by Django 5.0.7 on 2024-08-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_foodcategory_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
