# Generated by Django 5.0.7 on 2024-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_fooditem_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
