# Generated by Django 5.0.7 on 2024-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_foodtags_fooditem_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='name_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='foodtags',
            old_name='tag_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='restaurant_slug',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foodtags',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
