# Generated by Django 5.0.7 on 2024-08-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_name_slug_fooditem_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTags',
            new_name='FoodTag',
        ),
    ]
