# Generated by Django 5.0.7 on 2024-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_rename_foodtags_foodtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(related_name='food_items', to='restaurant.foodtag'),
        ),
    ]
