# Generated by Django 5.0.7 on 2024-08-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_fooditem_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtag',
            old_name='tag',
            new_name='name',
        ),
    ]
