# Generated by Django 5.0.7 on 2024-08-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_restaurant_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='tags',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodtag'),
        ),
    ]
