# Generated by Django 5.0.7 on 2024-09-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('cancel', 'cancel')], default='pending', max_length=30),
        ),
    ]
