# Generated by Django 5.0.7 on 2024-09-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=30),
        ),
    ]
