# Generated by Django 5.0.7 on 2024-08-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('orders', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='ordered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
        ),
    ]
