# Generated by Django 5.0.7 on 2024-08-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('orders', '0009_alter_orderdetails_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ordered_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
        ),
    ]
