# Generated by Django 5.0.7 on 2024-08-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderdetails_ordered_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='ordered_item',
        ),
    ]
