# Generated by Django 5.0.7 on 2024-08-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderdetails_ordered_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='ordered_food_items',
        ),
    ]
