# Generated by Django 5.0.7 on 2024-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderdetails_ordered_food_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='total',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
