# Generated by Django 5.0.7 on 2024-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_total_orderdetails_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='restaurant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
