# Generated by Django 5.0.7 on 2024-08-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderdetails_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
